import { NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

export async function GET() {
  // Calendar data is pre-generated by scripts/generate-calendar.ts to
  // public/data/calendar.json. The API route exists so dev mode and prod-static
  // mode share the same code path on the client (fetchData('/api/calendar')).
  const file = path.join(process.cwd(), 'public', 'data', 'calendar.json');
  if (!fs.existsSync(file)) {
    return NextResponse.json(
      { error: 'calendar.json not generated yet — run npx tsx scripts/generate-calendar.ts' },
      { status: 503 },
    );
  }
  const data = JSON.parse(fs.readFileSync(file, 'utf-8'));
  return NextResponse.json(data);
}
